#!/bin/bash
set -e

DEFAULT_MINICONDA_PATH=${HOME}/.miniconda3
INSTALLER_PATH=${HOME}/miniconda3-installer.sh

USER_CUSTOM_SH=${HOME}/.custom.sh
USER_CUSTOM_SH_BACKUP=${USER_CUSTOM_SH}.backup-miniconda

read -p "Path for miniconda installation ($DEFAULT_MINICONDA_PATH): " MINICONDA_PATH
MINICONDA_PATH=${MINICONDA_PATH:-$DEFAULT_MINICONDA_PATH}

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $INSTALLER_PATH
bash $INSTALLER_PATH -b -p $MINICONDA_PATH
rm $INSTALLER_PATH

echo "Backing up $USER_CUSTOM_SH to $USER_CUSTOM_SH_BACKUP"
cp $USER_CUSTOM_SH $USER_CUSTOM_SH_BACKUP

echo '
# Preempt environment configuration with user scoped installations
export CPATH=$HOME/.miniconda3/incude:$CPATH
export PATH=$HOME/.miniconda3/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.miniconda3/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$HOME/.miniconda3/lib/pkgconfig:$PKG_CONFIG_PATH
' >>$USER_CUSTOM_SH

echo
echo "Configuration complete! Log out and back in for changes to take effect."
